### ISSUE TITLE
Support RECthis Type Tag

### ISSUE THREAD

**Issue by cache-nez** [scalacenter/tasty-query#16]
Currently, ~~RECtype~~ RECthis tag is not supported by TreeUnpickler.

**Comment by bishabosha** [comment]
test case to exhibit the tag: https://github.com/scala/scala/blob/2.13.x/test/tasty/run/src-3/tastytest/RecTypes.scala

**Comment by bishabosha** [comment]
this might be closable already - looks like the treeunpickler handles this case
