### ISSUE TITLE
Read scala 2 standard library

### ISSUE THREAD

**Issue by cache-nez** [scalacenter/tasty-query#22]
At the moment, when a project is read, the standard library is not consumed, because it's mostly written in scala 2 and therefore no corresponding .tasty files exist. Therefore there are no definitions and no types from the standard library. 

The current workaround is to create a symbol whenever a definition from `scala.*` namespace is referenced. This adds stubs of definitions, but the relationships between types are still not understood. Therefore it is still essential to read the standard library somehow, either by parsing .class files or by compiling it with scala 3 and feeding the resulting files to the project reader.

The same challenge exists for Java and Scala 2 dependencies of the project.

**Comment by BarkingBad** [comment]
Scala 2 stdlib can have tasty files generated easily. To obtain them, in dotty repository run `sbt stdlib-bootstrapped/compile` and the output will be under `out/bootstrap/stdlib-bootstrapped/scala-<version>/classes`. Unfortunately, these files are not available yet as an artifact on maven so you have to get them manually.

**Comment by sjrd** [comment]
This was done as a byproduct of https://github.com/scalacenter/tasty-query/pull/63
