### ISSUE TITLE
Member throwError not found in symbol[object class reflect.report]

### ISSUE THREAD

**Issue by aymanelamyaghri** [scalacenter/tasty-query#334]
In dotty, in the node `throwError` of the tree of `QuotesImpl.valueOrAbort`, if we call `.symbol` it throws:

```
Member throwError[with sig (java.lang.String/T,scala.quoted.Expr/T):scala.Nothing/T @throwError] not found in symbol[object class reflect.report]
```

**Comment by sjrd** [comment]
The signed name we're looking for, which is directly read from TASTy, is
```
throwError[with sig (java.lang.String,scala.quoted.Expr):scala.Nothing @throwError]
```
but the one we compute for `throwError` is
```
throwError[with sig (java.lang.String,scala.quoted.Expr):scala.runtime.Nothing$ @throwError]
```
Apparently, signatures consider that the erasure of `scala.Nothing` is `scala.Nothing`, not the actual JVM-erased `scala.runtime.Nothing$` class.
