### ISSUE TITLE
Another MemberNotFoundException in com.softwaremill.sttp.model:core_2.13:1.0.2

### ISSUE THREAD

**Issue by adpi2** [scalacenter/tasty-query#398]
In [com.softwaremill.sttp.model:core_2.13:1.0.2](https://repo1.maven.org/maven2/com/softwaremill/sttp/model/core_2.13/1.0.2/):
```
tastyquery.Exceptions$MemberNotFoundException: Member UriContext[with sig (scala.StringContext):sttp.model.UriInterpolator.UriContext @UriContext] not found in PackageRef(sttp.client)
```

**Comment by sjrd** [comment]
> In [com.softwaremill.sttp.model:core_2.13:1.0.2](https://repo1.maven.org/maven2/com/softwaremill/sttp/model/core_2.13/1.0.2/):

Are you sure these are the right coordinates? There's no `sttp.client` at all in there. Only `sttp.model`.

**Comment by adpi2** [comment]
The right coordinates are: `com.softwaremill.sttp.client:core_2.13:2.0.4`
