### ISSUE TITLE
Implement types for all Trees/TypeTrees

### ISSUE THREAD

**Issue by bishabosha** [scalacenter/tasty-query#42]
All trees need to have a type, such that calling `.tpe` does not cause an exception.

types should be able to be constructed from information available at the creation of a tree, without requiring resolving of symbols. Sometimes types can be constructed by looking at the types of subtrees, but this should still be an operation that does not modify symbols.

Usually, the types of trees are already defined as a data type, sometimes however a new data type will have to be declared, (see https://github.com/scalacenter/tasty-query/issues/21)

Trees:
- [x] PackageDef
- [x] ImportSelector
- [x] Import
- [x] Export
- [x] ClassDef
- [x] TypeMember
- [x] TypeParam
- [x] Template
- [x] ValDef
- [x] DefDef
- [x] Ident
- [x] ReferencedPackage (special case of `Ident`)
- [x] Select
- [x] SelectIn
- [x] This
- [ ] Super
- [x] Apply
- [x] TypeApply
- [x] New
- [x] Typed
- [x] Assign
- [x] NamedArg
- [x] Block
- [x] If
- [x] InlineIf
- [ ] Lambda (need support for scala 2 types to create FunctionN)
- [x] Match
- [x] InlineMatch
- [x] CaseDef
- [x] Bind
- [ ] Alternative
- [ ] Unapply
- [ ] SeqLiteral
- [x] While
- [x] Throw
- [x] Try
- [x] Literal
- [x] Return
- [x] Inlined
- [x] EmptyTree

TypeTrees:
- [x] TypeIdent
- [x] TypeWrapper
- [x] SingletonTypeTree
- [ ] RefinedTypeTree
- [x] ByNameTypeTree
- [x] AppliedTypeTree
- [x] SelectTypeTree
- [x] TermRefTypeTree
- [x] AnnotatedTypeTree
- [ ] MatchTypeTree
- [x] TypeTreeBind
- [x] EmptyTypeTree
- [x] BoundedTypeTree
- [x] NamedTypeBoundsTree
- [x] TypeLambdaTree

**Comment by sjrd** [comment]
With #70 being merged, this is now as good as it needs to be for the time being. Shall we close this for the purpose of milestone https://github.com/scalacenter/tasty-query/milestone/1, and possibly later reopen individual cases?

**Comment by bishabosha** [comment]
agree, we have good types for a minimal subset
