### ISSUE TITLE
How to check if a Symbol has the override modifier ?

### ISSUE THREAD

**Issue by alexishorner** [scalacenter/tasty-query#439]
Hi !
I am rewriting the `ExtractAPI` phase of dotty using TASTy Query and I need to query if a `Symbol` has the `override` modifier.

Here is what the original dotty source code looks like (available in full [here](https://github.com/scala/scala3/blob/5973d9e6984cd276ef633a34a9244c806894a13e/compiler/src/dotty/tools/dotc/sbt/ExtractAPI.scala#L714-L720)):
```scala
def apiModifiers(sym: Symbol): api.Modifiers = {
  val absOver = sym.is(AbsOverride)
  val abs = absOver || sym.isOneOf(Trait | Abstract | Deferred)
  val over = absOver || sym.is(Override)
  new api.Modifiers(abs, over, [...])
}
```

My current solution boils down to doing
```scala
sym.flags.is(Override)
```
However, `Symbol.flags` is `protected`, so I invoke it using reflection, which does not seem like a great solution.

Does someone know a better way of checking if a `Symbol` has the `override` modifier ?
Thanks in advance for your assistance !

**Comment by bishabosha** [comment]
advice from @sjrd - ignore the override flag altogether - its not information that could ever require a downstream recompilation
