### ISSUE TITLE
Add a way to materialise Type / Symbol at compile time

### ISSUE THREAD

**Issue by bishabosha** [scalacenter/tasty-query#52]
It would be nice to have an API such as `typeOf[java.util.List[? <: String]]`, which returns a `tastyquery.ast.Type`. This could be implemented by using a scala 3 macro and the Quotes API. - This would likely only be used in the testing environment to begin with, and possibly become a mainstream API - I think this would make tests more readable. Possible complications are how to load the classpath in a macro.

**Comment by sjrd** [comment]
I don't think the cost/benefit ratio of this is small enough. I'm going to close it. If there are important use cases popping up at some point, we can revisit.
