### ISSUE TITLE
Module classes cannot be found unless their companion class is loaded first

### ISSUE THREAD

**Issue by sjrd** [scalacenter/tasty-query#72]
See the tests in `ReadTreeSuite` that use `testUnpickleTopLevel` and are marked with `FIXME`.

Maybe related: issues with `package$` package objects.

**Comment by bishabosha** [comment]
seems to only affect the empty package

**Comment by bishabosha** [comment]
the issue with empty package is just prepending the empty package to the `DeclarationPath`, ok but once you fix that issue, then there is still the case of initialising the tree - this needs more work
