### ISSUE TITLE
handle non-existing top-level class/object

### ISSUE THREAD

**Issue by bishabosha** [scalacenter/tasty-query#74]
e.g.
```scala
object Foo
```

will create `Foo$.class`, `Foo.class` and `Foo.tasty`. Currently tasty-query will enter roots:
- module class `EmptyPkg / objclass"Foo"`
- module value `EmptyPkg / name"Foo"`
- class `EmptyPkg / tname"Foo"`

however, we should never be able to access the class symbol from the user facing API, because it does not exist at the tasty level

**Comment by sjrd** [comment]
This was fixed in #77.
